version: '3'
services: 
  rabbitmq-server:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    hostname: rabbitmq-server
    ports: 
      - "8080:15672"
      - "25676:25676"
    